### ISSUE TITLE
Openstereo Error: cannot import name 'griddata' from 'matplotlib.mlab'

### ISSUE THREAD

**Issue by nazumpa** [spamlab-iee/os#23]
Olá, estou tentando abrir o openstereo no Ubuntu 20.4, já instalei tudo certinho mas na hora de abrir o openstereo pelo terminal ele retorna esta mensagem de erro:

ImportError: cannot import name 'griddata' from 'matplotlib.mlab'

Pelo que pude encontrar na internet, o matplotlib removeu esse griddata nas ultimas versões, não estou conseguindo adicioná-lo manualmente.

Alguem pode me ajudar?

**Comment by endarthur** [comment]
Por favor, tente desinstalar e reinstalar a versão mais atual, commitada agora pouco. Foi removida a dependência à versões antigas da matplotlib.

Please, try to unistall and reinstall the most recent version, just commited. The dependency on matplotlib's older versions was removed.

**Comment by nazumpa** [comment]
Funcionou!
